---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set IPv4
  set_fact:
    fts_ui_ipv4: 127.0.0.1

- name: Print IPv4
  debug:
    msg: "fts_ui_ipv4 = {{ fts_ui_ipv4 }}"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print fts_ui url
    - print fts_ui credentials
