---
name: SPLIT INSTALL (DOCKER)

"on":
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule_multiple_instances:
    name: Separation of Concern Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distros:
          - ubuntu2004
    steps:

      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            "${{ runner.os }}-pip-"

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule Install Test - Linux Playbook with Separation of Concern
        run: ANSIBLE_VERBOSITY=1 molecule test --scenario-name multiple_machines -- -e "webmap_force_install=true"
        env:
          MOLECULE_DISTRO: ${{ matrix.distros }}
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
