---
- name: Install FreeTAKServer and all components
  hosts: all
  become: true
  become_user: root
  roles:
    - freetakserver
    - freetakserver_ui
    - murmur
    - videoserver
    - nodered

  vars:

    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: false

    # Max seconds Node-RED Server will wait
    nodered_wait_for_videoserver_timeout: 600
    python3_version: "{{ lookup('env', 'py3_ver') | default('3.11', true) }}"


  pre_tasks:
    - name: Cleanup
      import_tasks: roles/common/tasks/cleanup.yml

    - name: Create fts user
      import_tasks: roles/common/tasks/create-fts-user.yml

  post_tasks:
    - name: Reload Node-RED Server flows to ensure Video Server connection
      import_tasks: roles/nodered/tasks/reload-flows.yml

    - name: Cleanup
      import_tasks: roles/common/tasks/cleanup.yml
