---
- name: Template config file
  template:
    src: webMAP_config.json.j2
    dest: "{{ webmap_config_location }}"
    owner: root
    group: root
    mode: 0644

- name: Template unit file
  become: true
  become_user: root
  template:
    src: webmap.service.j2
    dest: "{{ unit_files_location }}/{{ webmap_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "/opt/FTH-webmap-linux"

- name: Enable and set service
  include_tasks: ../../common/tasks/service.yml
  vars:
    service_name: "{{ webmap_service_name }}"
    service_enabled: "{{ webmap_enabled }}"
    service_state: "{{ webmap_state }}"
