---
- name: Template FTSConfig.yaml config file
  template:
    src: FTSConfig.yaml.j2
    dest: "{{ fts_config_path }}"
    owner: root
    group: root
    mode: 0644

- name: Change FirstStart to False in MainConfig.py
  lineinfile:
    path: "{{ fts_install_path }}/controllers/configuration/MainConfig.py"
    regexp: '(\s+)first_start = True'
    line: '\1first_start = False'
    backrefs: true

- name: Template unit file
  template:
    src: fts.service.j2
    dest: "{{ unit_files_location }}/{{ fts_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "FreeTAKServer.controllers.services.FTS"

- name: Enable and set service
  include_tasks: ../../common/tasks/service.yml
  vars:
    service_name: "{{ fts_service_name }}"
    service_enabled: "{{ fts_enabled }}"
    service_state: "{{ fts_state }}"

- name: Generate secure Administrator password
  set_fact:
    fts_admin_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
    fts_admin_token: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"

- name: Set FTS Administrator credentials
  block:
    - name: Wait until FTS REST API port is open
      wait_for:
        host: "{{ fts_public_ipv4 }}"
        port: "{{ fts_api_port }}"

    - name: Update the default FTS admin credentials
      uri:
        url: "http://{{ fts_public_ipv4 }}:19023/ManageSystemUser/putSystemUser"
        method: PUT
        headers:
          Content-Type: application/json
          Authorization: "Bearer token"
        unredirected_headers:
        body:
          systemUsers:
            - uid: "1"
              token: "token"
              password: "password"
        body_format: json
        status_code: 200
