---

- name: Template FTSConfig.yaml config file
  become: true
  become_user: fts
  template:
    src: FTSConfig.yaml.j2
    dest: "{{ fts_config_path }}"
    owner: fts
    group: fts
    mode: 0664

- name: Change FirstStart to False in MainConfig.py
  lineinfile:
    path: "{{ fts_install_path }}/{{ cfg_rpath }}/MainConfig.py"
    regexp: '(\s+)first_start = True'
    line: '\1first_start = False'
    backrefs: true

- name: Template unit file
  become: true
  become_user: root
  template:
    src: fts.service.j2
    dest: "{{ unit_files_location }}/{{ fts_service_name }}.service"
    owner: root
    group: root
    mode: 0664

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "FreeTAKServer.controllers.services.FTS"

- name: Enable and set service
  include_tasks: ../../common/tasks/service.yml
  vars:
    service_name: "{{ fts_service_name }}"
    service_enabled: "{{ fts_enabled }}"
    service_state: "{{ fts_state }}"
