---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include FTSConfig variables
  include_vars: "FTSConfig.yml"

- name: Get public IPv4
  uri:
    url: https://ifconfig.me/ip
    return_content: true
  register: ip_response

- name: Set public IPv4
  set_fact:
    fts_public_ipv4: "{{ ip_response.content }}"
  when: fts_ip_addr_extra is undefined

- name: Set public IPv4
  set_fact:
    fts_public_ipv4: "{{ fts_ip_addr_extra }}"
  when: fts_ip_addr_extra is defined

- name: Print IPv4
  debug:
    msg: "fts_public_ipv4 = {{ fts_public_ipv4 }}"

- name: Set localhost IPv4
  set_fact:
    fts_ipv4: 127.0.0.1

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"
