services:
  freetakserver:
    image: ghcr.io/freetakteam/freetakserver:latest
    hostname: freetakserver
    networks:
        - taknet
    volumes:
      - free-tak-core-db:/opt/fts/
    ports:
      # DataPackagePort
      - 8080:8080
      # CoTPort
      - 8087:8087
      # SSLCoTPort
      - 8089:8089
      # SSLDataPackagePort
      - 8443:8443
      # FederationPort
      - 9000:9000
      # APIPort - Don't expose by default
      - 19023:19023

    environment:
        # The ChangeMe section
        FTS_FED_PASSWORD: "defaultpass"
        FTS_CLIENT_CERT_PASSWORD: "supersecret"
        FTS_WEBSOCKET_KEY: "YourWebsocketKey"
        FTS_SECRET_KEY: "vnkdjnfjknfl1232#"
        #FTS_NODE_ID: "SOMESTRING"
        FTS_CONNECTION_MESSAGE: "Welcome to FreeTAKServer. The Parrot is not dead. It’s just resting"

        # Networking
        FTS_COT_PORT: 8087
        FTS_SSLCOT_PORT: 8089
        FTS_API_PORT: 19023
        FTS_FED_PORT: 9000

        FTS_DP_ADDRESS: 'freetakserver'
        FTS_USER_ADDRESS: 'freetakserver'
        FTS_API_ADDRESS: 'freetakserver'

        FTS_ROUTING_PROXY_SUBSCRIBE_PORT: 19030
        FTS_ROUTING_PROXY_SUBSCRIBE_IP: 'freetakserver'

        FTS_ROUTING_PROXY_PUBLISHER_PORT: 19032
        FTS_ROUTING_PROXY_PUBLISHER_IP: 'freetakserver'

        FTS_ROUTING_PROXY_SERVER_PORT: 19031
        FTS_ROUTING_PROXY_SERVER_IP: 'freetakserver'

        FTS_INTEGRATION_MANAGER_PULLER_PORT: 19033 # port to receive worker responses by the integration manager
        FTS_INTEGRATION_MANAGER_PULLER_ADDRESS: 'freetakserver' # address to receive worker responses by the integration manager

        FTS_INTEGRATION_MANAGER_PUBLISHER_PORT: 19034 # port from which to publish messages by the integration manager
        FTS_INTEGRATION_MANAGER_PUBLISHER_ADDRESS: 'freetakserver' # address from which to publish messages by the integration manager

        # Misc Settings
        FTS_OPTIMIZE_API: True
        FTS_DATA_RECEPTION_BUFFER: 1024
        FTS_MAX_RECEPTION_TIME: 4
        FTS_NUM_ROUTING_WORKERS: 3
        FTS_COT_TO_DB: True
        # number of milliseconds to wait between each iteration of main loop
        # decreasing will increase CPU usage and server performance
        # increasing will decrease CPU usage and server performance
        FTS_MAINLOOP_DELAY: 100
        FTS_EMERGENCY_RADIUS: 0 # radius of emergency within-which users will receive it
        FTS_LOG_LEVEL: "info"

  freetakserver-ui:
    image: ghcr.io/freetakteam/ui:latest
    hostname: freetakserver-ui
    networks:
        - taknet
    ports:
      - 5000:5000
    volumes:
      - free-tak-ui-db:/home/freetak/:Z,rw
    environment:
      FTS_IP: YOUR EXTERNAL URL HERE
      FTS_API_PORT: 19023
      FTS_API_PROTO: 'http'
      FTS_UI_EXPOSED_IP: 'freetakserver-ui'
      FTS_MAP_EXPOSED_IP: '127.0.0.1'
      FTS_MAP_PORT: 8000
      FTS_MAP_PROTO: 'http'
      FTS_UI_PORT: 5000
      FTS_UI_WSKEY: 'YourWebsocketKey'
      FTS_API_KEY: 'Bearer token'
      FTS_UI_SQLALCHEMY_DATABASE_URI: 'sqlite:////home/freetak/data/FTSServer-UI.db'

volumes:
  free-tak-core-db:
  free-tak-ui-db:

networks:
    taknet:
        driver: bridge
