services:
  fts:
    image: ghcr.io/freetakteam/freetakserver:latest
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: core-pypi.Dockerfile
    ports:
        # DataPackagePort
        - 8080:8080
        # CoTPort
        - 8087:8087
        # SSLCoTPort
        - 8089:8089
        # SSLDataPackagePort
        - 8443:8443
        # FederationPort - Don't expose unless you are trying to federate
        #- 9000:9000
        # APIPort - Don't expose unless you host UI and server on separate container networks
        #- 19023:19023
    volumes:
    # Confused about the Z at the end?
    # on hosts with selinux, you will need this.
    # a Z means the volume is not shared
    # a z means the volume is shared
      - ./base-config/:/opt/fts/:rw,Z
    network_mode: "host"

  free-tak-server-ui:
    image: ghcr.io/freetakteam/ui:latest
    ports:
      # Web interface port
      - 5000:5000
      # API Port - you probably don't need to expose if UI and Core are on same container network
      #- 19023:19023
    volumes:
        - free-tak-ui-db:/home/freetak/data/
    environment:
      FTS_IP: 'free-tak-server'
      FTS_API_PORT: 19023
      FTS_API_PROTO: 'http'
      FTS_UI_EXPOSED_IP: 'free-tak-server-ui'
      FTS_MAP_EXPOSED_IP: 'free-tak-server-ui'
      FTS_MAP_PORT: 8000
      FTS_MAP_PROTO: 'http'
      FTS_UI_PORT: 5000
      FTS_UI_WSKEY: 'YourWebsocketKey'
      FTS_API_KEY: 'Bearer token'
      FTS_UI_SQLALCHEMY_DATABASE_URI: 'sqlite:////home/freetak/data/FTSServer-UI.db'
volumes:
  free-tak-ui-db:
