#!/bin/bash
PYTHON_USER_SITE=$(python -m site --user-site)
# Detect and navigate to the python user site packages
# Some systems use `python3` instead of `python` so this is not entirely portable
cd "${PYTHON_USER_SITE}/FreeTAKServer-UI/" || raise error "Could not navigate to the user-sites path. Are you using a distro that requires python3 instead of python?"

# Check if there is *NOT* a config.py in the shared volume
if [[ ! -f "/home/freetak/data/config.py" ]]
  then
    # If there isn't, then we need to give one to the user
    cp ${PYTHON_USER_SITE}/FreeTAKServer-UI/config.bak /home/freetak/data/config.py
fi

# If the symlink has not been created yet, then we will do that
if [[ ! -f "${PYTHON_USER_SITE}/FreeTAKServer-UI/config.py" ]]
  then
    ln -s /home/freetak/data/config.py ${PYTHON_USER_SITE}/FreeTAKServer-UI/config.py
fi

# TODO This can be implemented once the FTS-UI has an SSL operation mode
# Check if SSL certificates in the shared volumes exists
#if -n compgen -G "/home/freetak/data/*.crt" > /dev/null || compgen -G "/home/freetak/data/*.key" > /dev/null
#  then
    # generate some certs
#    openssl req -x509 -newkey rsa:4096 -keyout autgenerated-key.pem -out autogenerated-cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=Unknown/L=Unknown/O=FreeTAKServer/OU=FTS-UI/CN=localhost"
#fi

# Now we can start the server
python run.py
