---
- name: Linux Playbook with Separation of Concern
  hosts: all
  become: true
  vars:

    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: false

  pre_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

  post_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

- hosts: noderedserver
  roles:
    - nodered
