---
- name: Template config file
  template:
    src: rtsp-simple-server.yml.j2
    dest: "{{ videoserver_config_location }}"
    owner: root
    group: root
    mode: 0664

- name: Template unit file
  become: true
  become_user: root
  template:
    src: rtsp-simple-server.service.j2
    dest: "{{ unit_files_location }}/{{ videoserver_service_name }}.service"
    owner: root
    group: root
    mode: 0664

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "rtsp-simple-server"

- name: Enable and set service
  include_tasks: ../../common/tasks/service.yml
  vars:
    service_name: "{{ videoserver_service_name }}"
    service_enabled: "{{ videoserver_enabled }}"
    service_state: "{{ videoserver_state }}"
