- name: Clone FreeTAKHub_VideoChecker repository
  git:
    repo: 'https://github.com/FreeTAKTeam/FreeTAKHub_VideoChecker.git'
    dest: '{{ playbook_dir }}'
    version: '{{ flow_branch }}'
    clone: yes
    update: yes
    register: git_clone_result

- name: Import Node-RED Videochecker flow via HTTP POST
  uri:
    url: "http://{{ noderedserver_ipv4 }}:{{ noderedserver_port }}/flow"
    method: POST
    headers:
      Content-Type: application/json
      Node-RED-API-Version: v1
      Node-RED-Deployment-Type: full
      Authorization: Bearer {{ nodered_admin_token }}
    body: "{{ lookup('file', playbook_dir + '/FreeTAKHub_VideoChecker/FreeTAKHub VideoChecker.json') }}"
    body_format: json
    status_code: 200
  when: git_clone_result.changed