- name: Make sure we have a 'fts' group
  group:
    name: fts
    state: present

- name: Allow 'fts' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers.d/80-ansible-fts-user
    state: present
    regexp: '^%fts'
    line: '%fts ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    mode: 0440

- name: Add fts user to fts group
  user:
    name: fts
    groups: fts,sudo
    append: yes
    state: present
    createhome: true

- name: Set up authorized keys for the deployer user
  authorized_key: user=fts key="{{item}}"
  with_file:
    - /home/fts/.ssh/id_rsa.pub
