---
- name: "Include Common {{ ansible_distribution }}-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Configure Path
  ansible.builtin.include_tasks:
    file: "configure-{{ ansible_distribution }}.yml"
#  ansible.builtin.vars:
#    fts_base_path: "{{ fts_base_path }}"
#    fts_venv: "{{ fts_venv }}"

- name: Setup
  ansible.builtin.include_tasks:
    file: "setup-{{ ansible_distribution }}.yml"
