---
- name: Enable service
  become: true
  become_user: root
  service:
    name: "{{ service_name }}"
    enabled: "{{ service_enabled }}"
    use: systemd
  register: enable_service
  retries: 20
  until: enable_service is success

- name: Set service state
  become: true
  become_user: root
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    use: systemd
  register: set_service_state
  retries: 20
  until: set_service_state is success
