---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: ip_response

- name: Set public IPv4
  set_fact:
    mumble_web_ipv4: "{{ ip_response.content }}"
  when: fts_ip_addr_extra is undefined

- name: Set public IPv4
  set_fact:
    mumble_web_ipv4: "{{ fts_ip_addr_extra }}"
  when: fts_ip_addr_extra is defined

- name: Print IPv4
  debug:
    msg: "mumble_web_ipv4 = {{ mumble_web_ipv4 }}"

- name: Install
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print mumble_web url
