---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: videoserver
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    pre_build_image: true
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:ro]

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
